### ISSUE TITLE
Different Fonts? Foreground Colour?

### ISSUE THREAD

**Issue by praveenscience** [rutikwankhade/CoverView#1]
I am planning to extend this project by adding support for choosing fonts and selecting foreground colours! 😁

Let's rock it! 🤘🏻

**Comment by rutikwankhade** [comment]
@praveenscience One of my friend has sent a huge PR which covered a few new features. So please check before contributing.

**Comment by praveenscience** [comment]
@rutikwankhade Sure... Will do.
