### ISSUE TITLE
Add option to upload custom logo or a user's Image

### ISSUE THREAD

**Issue by Rajesh-Royal** [rutikwankhade/CoverView#12]
![image](https://user-images.githubusercontent.com/24524924/164978593-776f0bd5-add2-4c5f-88e9-abf5038d5bfd.png)

**Comment by rutikwankhade** [comment]
Hey @Rajesh-Royal Thanks for the feedback. This feature has been added now. search custom in the icon section and upload your logo or image


https://user-images.githubusercontent.com/47467468/164988267-a5522197-b951-4a25-96c7-b9bef6958369.mp4
