### ISSUE TITLE
Generate thumbnail with GIF Images.

### ISSUE THREAD

**Issue by Rajesh-Royal** [rutikwankhade/CoverView#13]
**Current working**
- Upload a GIF Image, It shows a preview with GIF.

**Improvement Needed**
- Download the cover as GIF if the user has uploaded a GIF image for preview. 
- Right now It saves only the static Image.

https://user-images.githubusercontent.com/24524924/164978814-5efe6169-4a87-4853-b58e-6fa5431e875d.mp4

**Comment by rutikwankhade** [comment]
i don't think this is possible for this project right now. the library we use in coverview is dom2image and can convert the dom into a static image only. so no gif support
