### ISSUE TITLE
Ability to use Uploadcare file uploader for custom file/logo to be added 

### ISSUE THREAD

**Issue by shivaylamba** [rutikwankhade/CoverView#14]
Use uploadcare.com React File uploader widget to support uploading of items

**Comment by rutikwankhade** [comment]
This feature has been added now. Just search custom in the icon option and upload a logo or your own image. see it here
https://twitter.com/WankhadeRutik/status/1518270774335111168?s=20&t=9eT2L00K8KbpV2jp5JX1Ow

**Comment by shivaylamba** [comment]
@rutikwankhade my suggestion was to use the https://github.com/uploadcare/uploadcare-widget for choosing custom files.

**Comment by shivaylamba** [comment]
This also allows you to customize the image/ make edits into it before selecting it

**Comment by shivaylamba** [comment]
Please look into this @rutikwankhade if possible
