### ISSUE TITLE
Multilingual support: Simplified Chinese

### ISSUE THREAD

**Issue by thedavidweng** [rutikwankhade/CoverView#18]
Hi Rutik, CoverView is a great little tool, it would be better to have a simple language switch button.
I have already translated it, you can take a look [here](https://github.com/thedavidweng/CoverView-CN). It is also hosted on [Vercel](https://coverview-cn.vercel.app/)

**Comment by rutikwankhade** [comment]
Thank you for translating it. I appreciate it. @thedavidweng
