### ISSUE TITLE
No space between blog title text letter when i download the cover

### ISSUE THREAD

**Issue by unkwnownGriot** [rutikwankhade/CoverView#22]
After I don't know why but since this morning every time I download the cover the letters are completely stuck together and there is no space at all

## the issue in question:
![cover(7)](https://user-images.githubusercontent.com/83823820/212328531-73b50922-1f69-445c-bd8c-384b3c8ad2d7.png)

**Comment by rutikwankhade** [comment]
hey, i tried recreating this and didn't see any issues. I updated to a new version now. Can you please check again and see if this still persists ?

**Comment by unkwnownGriot** [comment]
hey i tried again but now there is another problem when i click on the download button it loads indefinitely and never stop

**Comment by rutikwankhade** [comment]
there was some issue with the patterns, rolled it back until fix. the loading issue is fixed.
