### ISSUE TITLE
Download button is not working properly

### ISSUE THREAD

**Issue by MusfiqDehan** [rutikwankhade/CoverView#25]
After applying many settings, the download button is loading only but not downloading. The download location is also wrong.

**Comment by rutikwankhade** [comment]
hey, this is fixed. i have pushed a temp solution for now. what do you mean by download location?

**Comment by MusfiqDehan** [comment]
Hey @rutikwankhade ,

Thanks for your reply and fix. The download button is working fine now.

I am using Linux OS for downloading. By default, the download location should be `Download` folder, but after click the Download button, the picture was downloaded in a random system folder. 

After manually fixing the `Download` folder, it is working fine.
