### ISSUE TITLE
custom icon should be the first option available while choosing icon

### ISSUE THREAD

**Issue by rutikwankhade** [rutikwankhade/CoverView#32]
currently users need to type custom to upload a custom icon, because of this a lot of users don't even know that this feature exists. also need an option to set as none

**Comment by RolandSmarzik** [comment]
Hi I would like to take over this issue.

**Comment by rutikwankhade** [comment]
Sure @RolandSmarzik , you can create a pr for this issue.

**Comment by rutikwankhade** [comment]
this has been fixed in the latest update https://github.com/rutikwankhade/CoverView/pull/37
