### ISSUE TITLE
Limit border size

### ISSUE THREAD

**Issue by 0xzim** [rutikwankhade/CoverView#8]
I randomly entered a large number for the border size and it grew big past the main container which I believe shouldn't be like that as shown in the image screenshot. So, I think a border size limit would be nice

![Screenshot (41)](https://user-images.githubusercontent.com/52291700/92167096-adacbe00-edee-11ea-8092-cff9eae386cc.png)

**Comment by rutikwankhade** [comment]
@Obizim Thank you for pointing it out. Great find. I will fix it.
